name: TestRun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: echo "Repository Checked Out" >> Checkout.text

      - name: Share File Via FileStack
        uses: Warhammer4000/FileStack-Share-Artifact@main # This is the action
        id: filestack
        with:
              API_KEY: ${{secrets.FILESTACK_API}}
              FILE_PATH: Checkout.text
      - name: Get the output url
        run: echo "Download Link is:${{ steps.filestack.File_LINK.time }}"   
        
